FROM rocker/r-ver:latest

# Install the linux libraries needed
RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev \
  libgdal-dev \
  libproj-dev  \
  gdal-bin

# Install mongo prerequisites
RUN apt-get install -y libssl-dev libsasl2-dev libudunits2-dev

# Install R packages
RUN R -e "install.packages('rgdal')"
RUN R -e "install.packages('raster')"
RUN R -e "install.packages('gdalUtils')"
RUN R -e "install.packages('rgeos')"
RUN R -e "install.packages('plumber')"
RUN R -e "install.packages('foreign')"
RUN R -e "install.packages('landscapemetrics')"
RUN R -e "install.packages('mongolite')"
RUN R -e "install.packages('aws.s3')"
RUN R -e "install.packages('gdalUtilities')"
RUN R -e "install.packages('rasterDT')"
RUN R -e "install.packages('rvest')"
RUN R -e "install.packages('dplyr')"
RUN R -e "install.packages('forestChange')"



# Assign the temporal folder in the external drive
RUN R -e "write('TMP = "/data/tempR"', file=file.path(Sys.getenv('R_USER'), '.Renviron'))"

# Copy everything from the current directory into the container
COPY / /

# Install forestChange from .tar
RUN R -e "install.packages('forestChange_1.0.tar.gz', repos = NULL, type = 'source')"

# open port 8000 to traffic
EXPOSE 8000

# Call main script
ENTRYPOINT ["Rscript", "main.R"]
