version: '3.6'
services:
  api:
    build: .
    image: forest4water:latest
    container_name: forest4water
    restart: always
    ports:
      - 8000:8000
    deploy:
     replicas: 5
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
    volumes:
     - /data:/data
    networks:
      forest4water_net:
        aliases:
            - "api"

  load_balancer:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports: 
        - "8080:80"
    volumes: 
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
        - forest4water_net
    depends_on: 
        - api
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  forest4water_net:
    driver: overlay
